import "./globals.css";

import { Inter } from "next/font/google";
import { Toaster } from 'sonner'


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className='bg-slate-200'>
        {children}
        <span>
          <Toaster
            richColors
            position="top-right"
          />
        </span>
      </body>
    </html>
  );
}
