import "./globals.css";

import Sidebar from "@/components/Sidebar";

import { Toaster } from 'sonner'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className='bg-slate-200 flex'>
        <Sidebar />
        <div className="flex flex-col flex-grow p-10">
          {children}
        </div>
        <span>
          <Toaster
            richColors
            position="top-right"
          />
        </span>
      </body>
    </html>
  );
}
